"""Dependency-free scalar/vector GVP message passing for protein solubility."""
from __future__ import annotations
import torch
from torch import nn

def vector_linear(v,weight):return torch.einsum('...vc,ov->...oc',v,weight)
class GVPMessageLayer(nn.Module):
 def __init__(self,scalar_dimension=128,vector_dimension=16,dropout=.1):
  super().__init__();self.register_buffer('centers',torch.linspace(0,20,16));self.scale=20/15;self.vector_weight=nn.Parameter(torch.empty(vector_dimension,vector_dimension*2+1));nn.init.xavier_uniform_(self.vector_weight);edge_dimension=scalar_dimension+16+vector_dimension;self.scalar_message=nn.Sequential(nn.LayerNorm(edge_dimension),nn.Linear(edge_dimension,scalar_dimension),nn.GELU(),nn.Dropout(dropout),nn.Linear(scalar_dimension,scalar_dimension));self.vector_gate=nn.Linear(scalar_dimension,vector_dimension);self.attention=nn.Linear(scalar_dimension,1);self.scalar_update=nn.Sequential(nn.LayerNorm(scalar_dimension*2),nn.Linear(scalar_dimension*2,scalar_dimension),nn.GELU(),nn.Dropout(dropout));self.vector_update_gate=nn.Linear(scalar_dimension,vector_dimension)
 def forward(self,s,v,coords,neighbors,distances,mask):
  batch=torch.arange(len(s),device=s.device)[:,None,None];ns=s[batch,neighbors.long()];nv=v[batch,neighbors.long()];nc=coords[batch,neighbors.long()];direction=(nc-coords[:,:,None]);direction=direction/direction.norm(dim=-1,keepdim=True).clamp_min(1e-6);vm=vector_linear(torch.cat((nv,v[:,:,None].expand_as(nv),direction[...,None,:]),-2),self.vector_weight);vn=vm.norm(dim=-1);rbf=torch.exp(-((distances[...,None]-self.centers)/self.scale).square());sm=self.scalar_message(torch.cat((ns-s[:,:,None],rbf,vn),-1));vm=vm*torch.sigmoid(self.vector_gate(sm))[...,None];weights=torch.softmax(self.attention(sm).squeeze(-1),2);sa=(sm*weights[...,None]).sum(2);va=(vm*weights[...,None,None]).sum(2);s=s+self.scalar_update(torch.cat((s,sa),-1))*mask[...,None];v=(v+va*torch.sigmoid(self.vector_update_gate(s))[...,None])*mask[...,None,None];return s,v
class GVPStructureFusion(nn.Module):
 def __init__(self,sequence_dimension,input_scalar_dimension,scalar_dimension=128,vector_dimension=16,representation_dimension=256,dropout=.2,layers=2,fusion='interaction'):
  super().__init__();self.fusion=fusion;self.scalar_input=nn.Sequential(nn.LayerNorm(input_scalar_dimension),nn.Linear(input_scalar_dimension,scalar_dimension),nn.GELU());self.vector_input=nn.Parameter(torch.empty(vector_dimension,8));nn.init.xavier_uniform_(self.vector_input);self.layers=nn.ModuleList([GVPMessageLayer(scalar_dimension,vector_dimension,dropout) for _ in range(layers)]);self.residue_project=nn.Sequential(nn.LayerNorm(scalar_dimension+vector_dimension),nn.Linear(scalar_dimension+vector_dimension,representation_dimension),nn.GELU());self.attention=nn.Linear(representation_dimension,1);self.sequence=nn.Sequential(nn.LayerNorm(sequence_dimension),nn.Linear(sequence_dimension,512),nn.GELU(),nn.Dropout(dropout),nn.Linear(512,representation_dimension),nn.GELU());head_dimension=representation_dimension*(4 if fusion=='interaction' else 2);self.head=nn.Sequential(nn.LayerNorm(head_dimension),nn.Linear(head_dimension,representation_dimension),nn.GELU(),nn.Dropout(dropout),nn.Linear(representation_dimension,1))
 def forward(self,sequence,residue,vectors,coords,mask,neighbors,distances):
  s=self.scalar_input(residue);v=vector_linear(vectors,self.vector_input)*mask[...,None,None]
  for layer in self.layers:s,v=layer(s,v,coords,neighbors,distances,mask)
  z=self.residue_project(torch.cat((s,v.norm(dim=-1)),-1));logits=self.attention(z).squeeze(-1).masked_fill(~mask,-torch.inf);pooled=(z*torch.softmax(logits,1)[...,None]).sum(1);seq=self.sequence(sequence);features=(seq,pooled,seq*pooled,(seq-pooled).abs()) if self.fusion=='interaction' else (seq,pooled);return self.head(torch.cat(features,1)).squeeze(-1)
