"""Dependency-free scalar/vector GVP message passing for protein solubility."""
from __future__ import annotations
import torch
from torch import nn

def vector_linear(v,weight):return torch.einsum('...vc,ov->...oc',v,weight)
class GVPMessageLayer(nn.Module):
 def __init__(self,scalar_dimension=128,vector_dimension=16,dropout=.1):
  super().__init__();self.register_buffer('centers',torch.linspace(0,20,16));self.scale=20/15;self.vector_weight=nn.Parameter(torch.empty(vector_dimension,vector_dimension*2+1));nn.init.xavier_uniform_(self.vector_weight);edge_dimension=scalar_dimension+16+vector_dimension;self.scalar_message=nn.Sequential(nn.LayerNorm(edge_dimension),nn.Linear(edge_dimension,scalar_dimension),nn.GELU(),nn.Dropout(dropout),nn.Linear(scalar_dimension,scalar_dimension));self.vector_gate=nn.Linear(scalar_dimension,vector_dimension);self.attention=nn.Linear(scalar_dimension,1);self.scalar_update=nn.Sequential(nn.LayerNorm(scalar_dimension*2),nn.Linear(scalar_dimension*2,scalar_dimension),nn.GELU(),nn.Dropout(dropout));self.vector_update_gate=nn.Linear(scalar_dimension,vector_dimension)
 def forward(self,s,v,coords,neighbors,distances,mask,confidence=None):
  batch=torch.arange(len(s),device=s.device)[:,None,None];indices=neighbors.long();pairwise=indices[..., :,None]==indices[...,None,:];duplicate=torch.tril(pairwise,diagonal=-1).any(-1);valid=mask[batch,indices]&mask[:,:,None]&(distances>1e-6)&torch.isfinite(distances)&~duplicate;ns=s[batch,indices];nv=v[batch,indices];nc=coords[batch,indices];direction=(nc-coords[:,:,None]);direction=direction/direction.norm(dim=-1,keepdim=True).clamp_min(1e-6);vm=vector_linear(torch.cat((nv,v[:,:,None].expand_as(nv),direction[...,None,:]),-2),self.vector_weight);vn=vm.norm(dim=-1);rbf=torch.exp(-((distances[...,None]-self.centers)/self.scale).square())*valid[...,None];sm=self.scalar_message(torch.cat((ns-s[:,:,None],rbf,vn),-1));edge_product=(confidence[:,:,None]*confidence[batch,indices] if confidence is not None else torch.ones_like(distances));edge_gate=torch.sqrt(edge_product.clamp_min(1e-8))*valid;sm=sm*edge_gate[...,None];vm=vm*torch.sigmoid(self.vector_gate(sm))[...,None]*edge_gate[...,None,None];weights=torch.softmax((self.attention(sm).squeeze(-1)+edge_gate.clamp_min(1e-6).log()).masked_fill(~valid,-1e4),2)*valid;weights=weights/weights.sum(2,keepdim=True).clamp_min(1e-8);sa=(sm*weights[...,None]).sum(2);va=(vm*weights[...,None,None]).sum(2);node_gate=confidence if confidence is not None else mask;s=s+self.scalar_update(torch.cat((s,sa),-1))*node_gate[...,None];v=(v+va*torch.sigmoid(self.vector_update_gate(s))[...,None])*node_gate[...,None,None];return s,v
class GVPStructureFusion(nn.Module):
 def __init__(self,sequence_dimension,input_scalar_dimension,scalar_dimension=128,vector_dimension=16,representation_dimension=256,dropout=.2,layers=2,fusion='interaction',residue_sequence_dimension=0,rsa_mean=0.,rsa_std=1.,surface_patches=False):
  super().__init__();self.fusion=fusion;self.residue_sequence_dimension=residue_sequence_dimension;self.rsa_mean=float(rsa_mean);self.rsa_std=float(rsa_std);structure_dimension=input_scalar_dimension-residue_sequence_dimension if fusion=='aligned_moe' else input_scalar_dimension;self.scalar_input=nn.Sequential(nn.LayerNorm(structure_dimension),nn.Linear(structure_dimension,scalar_dimension),nn.GELU());self.vector_input=nn.Parameter(torch.empty(vector_dimension,8));nn.init.xavier_uniform_(self.vector_input);self.layers=nn.ModuleList([GVPMessageLayer(scalar_dimension,vector_dimension,dropout) for _ in range(layers)]);self.residue_project=nn.Sequential(nn.LayerNorm(scalar_dimension+vector_dimension),nn.Linear(scalar_dimension+vector_dimension,representation_dimension),nn.GELU());self.attention=nn.Linear(representation_dimension,1);self.sequence=nn.Sequential(nn.LayerNorm(sequence_dimension),nn.Linear(sequence_dimension,512),nn.GELU(),nn.Dropout(dropout),nn.Linear(512,representation_dimension),nn.GELU())
  self.surface_patches=bool(surface_patches)
  if fusion=='aligned_moe':self.residue_confidence=nn.Sequential(nn.Linear(4,16),nn.GELU(),nn.Linear(16,1),nn.Sigmoid());self.protein_confidence=nn.Sequential(nn.Linear(5,16),nn.GELU(),nn.Linear(16,1),nn.Sigmoid());self.residue_sequence=nn.Sequential(nn.LayerNorm(residue_sequence_dimension),nn.Linear(residue_sequence_dimension,representation_dimension),nn.GELU());self.aligned=nn.Sequential(nn.LayerNorm(representation_dimension*4+1),nn.Linear(representation_dimension*4+1,representation_dimension),nn.GELU(),nn.Dropout(dropout));self.sequence_head=nn.Linear(representation_dimension,1)
  if self.surface_patches:
   if fusion!='aligned_moe':raise ValueError('surface patch tokens require aligned_moe fusion')
   self.surface_patch_token=nn.Sequential(nn.LayerNorm(representation_dimension+13),nn.Linear(representation_dimension+13,representation_dimension),nn.GELU(),nn.Dropout(dropout));self.surface_patch_attention=nn.MultiheadAttention(representation_dimension,4,dropout=dropout,batch_first=True);self.surface_patch_query=nn.Parameter(torch.randn(1,1,representation_dimension)*.02);self.surface_patch_merge=nn.Sequential(nn.Linear(representation_dimension*2,representation_dimension),nn.GELU());self.surface_residue_attention=nn.MultiheadAttention(representation_dimension,4,dropout=dropout,batch_first=True);self.surface_residue_merge=nn.Sequential(nn.LayerNorm(representation_dimension*2),nn.Linear(representation_dimension*2,representation_dimension),nn.GELU());self.surface_patch_head=nn.Sequential(nn.LayerNorm(representation_dimension),nn.Linear(representation_dimension,representation_dimension//2),nn.GELU(),nn.Dropout(dropout),nn.Linear(representation_dimension//2,1))
  self.last_surface_patch_logit=None
  head_dimension=representation_dimension*(4 if fusion in ('interaction','aligned_moe') else 2);self.head=nn.Sequential(nn.LayerNorm(head_dimension),nn.Linear(head_dimension,representation_dimension),nn.GELU(),nn.Dropout(dropout),nn.Linear(representation_dimension,1))
 def pool_surface_patches(self,z,patch,plddt,rsa,mask,component_ids,confidence):
  batch_size,_,categories=component_ids.shape;valid=(component_ids>=0)&mask[...,None];batch_ids=torch.arange(batch_size,device=z.device)[:,None,None].expand_as(component_ids);category_ids=torch.arange(categories,device=z.device)[None,None,:].expand_as(component_ids);label_stride=int(component_ids[valid].max())+2 if valid.any() else 1;group_ids=((batch_ids*categories+category_ids)*label_stride+component_ids.clamp_min(0))[valid];unique,inverse=torch.unique(group_ids,sorted=True,return_inverse=True);groups=len(unique);meta=unique//label_stride;group_batches=meta//categories;group_categories=meta%categories;residue_z=z[:,:,None,:].expand(-1,-1,categories,-1)[valid];rsa_values=rsa[...,None].expand_as(component_ids)[valid];plddt_values=plddt[...,None].expand_as(component_ids)[valid];hydropathy=patch[...,0,None].expand_as(component_ids)[valid];confidence_values=confidence[...,None].expand_as(component_ids)[valid];weights=(rsa_values*confidence_values).clamp_min(1e-6).to(z.dtype);denominator=torch.zeros(groups,device=z.device,dtype=z.dtype).index_add_(0,inverse,weights);embedding=torch.zeros(groups,z.shape[-1],device=z.device,dtype=z.dtype).index_add_(0,inverse,residue_z*weights[:,None])/denominator[:,None].clamp_min(1e-6);ones=torch.ones_like(weights);size=torch.zeros_like(denominator).index_add_(0,inverse,ones);rsa_sum=torch.zeros_like(denominator).index_add_(0,inverse,rsa_values.to(z.dtype));plddt_sum=torch.zeros_like(denominator).index_add_(0,inverse,plddt_values.to(z.dtype));hydropathy_sum=torch.zeros_like(denominator).index_add_(0,inverse,hydropathy.to(z.dtype));plddt_min=torch.full_like(denominator,float('inf')).scatter_reduce_(0,inverse,plddt_values.to(z.dtype),reduce='amin',include_self=True);hydropathy_max=torch.full_like(denominator,-float('inf')).scatter_reduce_(0,inverse,hydropathy.to(z.dtype),reduce='amax',include_self=True);category_onehot=torch.nn.functional.one_hot(group_categories,categories).to(z.dtype);descriptors=torch.cat((torch.stack((torch.log1p(size)/5,rsa_sum/10,rsa_sum/size,plddt_sum/size,plddt_min,hydropathy_sum/size,hydropathy_max,denominator/size),-1),category_onehot),-1);tokens=self.surface_patch_token(torch.cat((embedding,descriptors),-1));scores=rsa_sum*plddt_sum/size.clamp_min(1);batches=[]
  for batch_index in range(batch_size):
   selected=torch.where(group_batches==batch_index)[0];selected=selected[torch.topk(scores[selected],min(64,len(selected))).indices] if len(selected) else selected;batches.append(tokens[selected] if len(selected) else z.new_zeros(1,z.shape[-1]))
  maximum=max(map(len,batches));padded=z.new_zeros(batch_size,maximum,z.shape[-1]);patch_mask=torch.zeros(batch_size,maximum,dtype=torch.bool,device=z.device)
  for batch_index,values in enumerate(batches):padded[batch_index,:len(values)]=values;patch_mask[batch_index,:len(values)]=True
  contextual,_=self.surface_patch_attention(padded,padded,padded,key_padding_mask=~patch_mask,need_weights=False);query=self.surface_patch_query.expand(batch_size,-1,-1);pooled,_=self.surface_patch_attention(query,contextual,contextual,key_padding_mask=~patch_mask,need_weights=False);return pooled[:,0],contextual,patch_mask
 def forward(self,sequence,residue,vectors,coords,mask,neighbors,distances,patch=None,patch_components=None):
  self.last_surface_patch_logit=None
  confidence=None;structure=residue[...,:-self.residue_sequence_dimension] if self.fusion=='aligned_moe' else residue
  if self.fusion=='aligned_moe':
   plddt=structure[...,151].clamp(0,1);rsa=(structure[...,63]*self.rsa_std+self.rsa_mean).clamp(0,1);batch=torch.arange(len(residue),device=residue.device)[:,None,None];valid=mask[batch,neighbors.long()]&mask[:,:,None]&(distances>1e-6);neighbor_conf=(plddt[batch,neighbors.long()]*valid).sum(2)/valid.sum(2).clamp_min(1);confidence=self.residue_confidence(torch.stack((plddt,neighbor_conf,rsa,structure[...,141]),-1)).squeeze(-1)*plddt*mask
  s=self.scalar_input(structure)*(confidence[...,None] if confidence is not None else mask[...,None]);v=vector_linear(vectors,self.vector_input)*(confidence[...,None,None] if confidence is not None else mask[...,None,None])
  for layer in self.layers:s,v=layer(s,v,coords,neighbors,distances,mask,confidence)
  z=self.residue_project(torch.cat((s,v.norm(dim=-1)),-1));seq=self.sequence(sequence);surface_pooled=None
  if self.fusion=='aligned_moe':
   sequence_tokens=self.residue_sequence(residue[...,-self.residue_sequence_dimension:])*mask[...,None]
   if self.surface_patches:
    if patch is None or patch_components is None:raise ValueError('surface patch descriptors and component ids are required')
    surface_pooled,surface_tokens,surface_mask=self.pool_surface_patches(z,patch,plddt,rsa,mask,patch_components,confidence);self.last_surface_patch_logit=self.surface_patch_head(surface_pooled).squeeze(-1);surface_context,_=self.surface_residue_attention(sequence_tokens,surface_tokens,surface_tokens,key_padding_mask=~surface_mask,need_weights=False);sequence_tokens=self.surface_residue_merge(torch.cat((sequence_tokens,surface_context),-1))*mask[...,None]
   z=self.aligned(torch.cat((sequence_tokens,z,sequence_tokens*z,(sequence_tokens-z).abs(),confidence[...,None]),-1))*confidence[...,None]
  logits=self.attention(z).squeeze(-1).masked_fill(~mask,-torch.inf);pooled=(z*torch.softmax(logits,1)[...,None]).sum(1)
  if self.fusion=='aligned_moe':
   if surface_pooled is not None:pooled=self.surface_patch_merge(torch.cat((pooled,surface_pooled),-1))
   count=mask.sum(1).clamp_min(1);quality=torch.stack(((plddt*mask).sum(1)/count,((plddt<.7)&mask).sum(1)/count,torch.log1p(count)/10,confidence.sum(1)/count,(rsa*mask).sum(1)/count),-1);gate=quality[:,0]*self.protein_confidence(quality).squeeze(-1);joint=self.head(torch.cat((seq,pooled*gate[:,None],seq*pooled*gate[:,None],(seq-pooled).abs()*gate[:,None]),-1)).squeeze(-1);return (1-gate)*self.sequence_head(seq).squeeze(-1)+gate*joint
  features=(seq,pooled,seq*pooled,(seq-pooled).abs()) if self.fusion=='interaction' else (seq,pooled);return self.head(torch.cat(features,1)).squeeze(-1)
